### ISSUE TITLE
sidebar.html: 'access_level' blocks

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#13]
Suggest changing `ifgt` to `ifge` in sidebar.html:
### old
`<~admin80_menu ifgt="SESSION[access_level]" value="80" inline>`
### new
`<~admin80_menu ifge="SESSION[access_level]" value="80" inline>`

Because it's natural to count by tens. Consider the following:

Value | Category
------------ | -------------
100 | Admin
90 | Supervisor
80 | Manger

To display manager menu, I have to 
`<~admin80_menu ifgt="SESSION[access_level]" value="79" inline>`

that  doesn't align with having access_level value of **80** in tag name `<~admin80` and comparison value of **79**.

**Comment by osalabs** [comment]
Fixed some time ago
