### ISSUE TITLE
PHP coding convention: equation with ''

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#16]
Why do we need all these `== ''` equations in conditionals, for example:

````
if ( $this->list_filter['sortby'] == '') {
````
why just not using:

````
if (!$this->list_filter['sortby']) {`
````

http://php.net/manual/en/types.comparisons.php

**Comment by osalabs** [comment]
basically it's the same.
To avoid php notices you might want to use `if ( !isset($this->list_filter['sortby']) )`

I won't restrict such coding style, it's up to the developer.
