### ISSUE TITLE
$list_sortdef : order by several columns

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#17]
It would be nice to order by arbitrary number of columns in lists utilizing default `$list_sortdef`
````
public $list_sortdef = 'id asc, title desc, othercolumn';
````

Currently we need to override `setListSorting()`:

```
public function setListSorting() {
    if ( $this->list_filter['sortby'] == '') {
        $this->list_orderby = $this->list_sortdef;
    } else {
        parent::setListSorting();
    }
}
```

**Comment by osalabs** [comment]
No, you are using `$list_sortdef` in a wrong way.
`$list_sortdef` - only defines public sort name (and optionally `desc`)
Then we have `$list_sortmap` which translates public sort name (potentially dangerous) to actual db fields (could be multiple).
For example:
```
public $list_sortdef = 'pubname';
public $list_sortmap = array(                   //sorting map: req param name => sql field name(s) asc|desc direction
                        'pubname'         => 'id asc, title desc, othercolumn',
                        );
```

**Comment by vladsavchuk** [comment]
Thanks. At last I fully understand what is `$list_sortmap` used for.
