### ISSUE TITLE
Proper place for site-wide JS file

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#18]
I've created `site.js` to implement instant language switching through AJAX-request and location reload. 
I need this JS-file on every page, so I added to the `/layout/sys_footer.html` the following:
````
<script src="<~ROOT_URL>/js/site/site.js"></script>
````
Should we provide empty `site.js` and recommend to use it like `site.css`? 
I definitely don't want to add site-specific code into `fw.js`.

**Comment by osalabs** [comment]
well, some sites without much frontend coding might not require common site js at all.
It's more like "recommendation" and just add to documentation
