### ISSUE TITLE
Documentation: Routing

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#20]
I need a comprehensive description about routing.

Probably a two-column table like **'HTTP_METHOD/URL_PATH ---> Corresponding handler in Controller (function name of the action)'**.

I'm still confused about `const route_default_action = ''`, and why the values are in lowercase ('index', 'show') when the function names are capitalized ('IndexAction', 'ShowAction') ...

**Comment by osalabs** [comment]
Done in https://github.com/osalabs/osafw-asp.net#rest-mappings
