### ISSUE TITLE
Best practice: form autosubmit only for selected inputs 

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#22]
I have the form with autosubmit (`data-check-changes`, `data-autosave` are set):

![image](https://user-images.githubusercontent.com/35847544/35779035-79aa1b80-09cf-11e8-9578-03937e489fdc.png)

My question is regarding **Birth Date** section.
I want to autosubmit only if the all 3 `select`s are set, or at least if the last **Year** `select` is set.

What is the best approach for it? Do we have an inbox solution in `fw.js`?

**Comment by osalabs** [comment]
You can do this:
- for each `select` add `data-nosubmit`
- then use custom `onload.js` to trigger submit once all 3 selects set
