### ISSUE TITLE
Best practice: implement JSON API

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#24]
If I want to implement some API-service that talks only in JSON format.
What would be the best approach?

1. Is it good to put `$this->fw->route->format = 'json';` into `__construct` for every Controller?
2. If I have a lot of custom actions in some Controller how to avoid setting `_json => true` for every `$ps` returned? Create some `private function postActionAlterPs(&$ps)`or global one in SiteUtils and pass $ps to it in every action? 
3. Or just create base JSON Controller class that extends `FwController` and then inherit from it?

I think we need some basic guides describing how to do common things.

**Comment by osalabs** [comment]
3. is the best approach - we could have FwApiController which will implement all necessary support for JSON API's. Then developers just extend this controller like ApiStuffController
And we could have  `/Api` route prefix, so URLs will be like `/Api/Stuff`.

**Comment by osalabs** [comment]
Closing as now there are `FwApiController`, see `v1NoopController` for API controller example.
Basically:
- on config we have `ROUTE_PREFIXES`, and we have /v1 here (for API version 1)
- then on `/php/controllers/v1` folder we can create api controllers inherited from `FwApiController`
- so it's accessible via REST endpoint `/v1/controllername`

Note, for auth supported out of the box:
- php sessions
- basic API key 
  - if set in `fw->config->API_KEY`
  - used header - "Authorization: Basic BASE64_ENCODED_KEY"
- JWT tokens
  - requires [Firebase JWT library](https://github.com/firebase/php-jwt)
  - set required `fw->config->JWT_SECRET`
  - set optional `fw->config->JWT_ISSUER`
  - set optional `fw->config->JWT_AUDIENCE`
  - set optional `fw->config->JWT_EXPIRATION` (default 3600)

see `FwApiController->auth()`
