### ISSUE TITLE
Best practice: PJAX and $ps['_layout']

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#27]
1. Should I use the `$ps['_layout']` to override the default layout?
2. Is `$ps['_layout']` undocumented feature or hack? 
3. Perhaps it'd be better to use some FW prefix for such kind of overrides, like `$ps['_fw_layout']`.

### Use Case

I have an AJAX-request to get a list of `<option>`s for the `<select>`ed value. 
I don't want to use default `layout_pjax.html` because of extra `<script>` block and the content of `<~main> is escaped by default.

So, I've created `/site/layout_pjax_nojs_noescape.html` with the following content:
```
<~main noescape>
```
And then in the Controller:

````php
public function getSelectOptionsAction() {
    $ps = array(
        '_layout' => '/site/layout_pjax_nojs_noescape.html',
        'main' => $this->model->getSelectOptions(reqs('parent_id'))
    );

    return $ps;
}
````
Or should I just simply do:

````php
function getSelectOptionsAction() {
    echo $this->model->getSelectOptions(reqs('parent_id'));
}
````

**Comment by osalabs** [comment]
1. Yes, if you want to override layout for specific action, see #26 
2. It's official feature, not a hack
3. Let's keep it simple `$ps['_layout']` as normal field names should never start with `_`

For your use case - fw already capable to detect PJAX request and uses layout `/layout_pjax.html`, therefore you don't need to recreate this functionality like you described (unless you want something custom). 

Best approach for PJAX actions:

```
function OptionsAction($id) {
  $id+=0;
   return array(
       'options' => $this->model->getSelectOptions($id);
   );
}
```

in the `/controller/options/main.html`:
```
<~options noescape>
```
(and it's also possible to have `/controller/options/onload.js` and `/controller/options/head.js` which is supported by `/layout_pjax.html`)

and in the js code:
```
$element.load('/Controller/(Options)/123');
```
