### ISSUE TITLE
Uploads: long titles/names overlap with images

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#30]
`/Admin/Att` Is it okay?

![image](https://user-images.githubusercontent.com/35847544/36063325-38406bc2-0e84-11e8-88ff-099642a7f6ae.png)

**Comment by osalabs** [comment]
yes, it's OK, I've moved images to `TD` background, instead of `IMG` with float-right.
This way they won't take space and it's just a preview
