### ISSUE TITLE
Dynamic Control: attrs_control

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#39]
How to use it properly?

```"attrs_control": "data-live-search='true"``` results to the following html:
```data-live-search=&quot;true&quot;```

```"attrs_control": "data-live-search=true"``` results to the following html:
```data-live-search=true```

The last one works but I want it to be pretty in html:
```data-live-search="true"```

Should the **attrs_control** be default with noescape attibute?
```<~attrs_control noescape>```

**Comment by osalabs** [comment]
Fixed
