### ISSUE TITLE
Sidebar is not adaptive

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#4]
### Side menu is not folded on small screens

![image](https://user-images.githubusercontent.com/35847544/35639751-def9dcd2-06c3-11e8-84c6-5459a105abac.png)

### Suggest some simple fold/unfold button

![image](https://user-images.githubusercontent.com/35847544/35639851-2b9e091e-06c4-11e8-9115-a2384a8dca92.png)

**Comment by vladsavchuk** [comment]
### Possible implementation

```
<div class="d-block d-md-none text-center mb-1">
  <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-expanded="false" aria-controls="sidebarMenu">
     <span class="dropdown-toggle">`Member's Menu`</span>
  </button>
</div>

<div id="sidebarMenu" class="sidebar-nav collapse d-md-block mb-4">
  <ul class="nav flex-column">
...
  </ul>
</div>
```

**Comment by osalabs** [comment]
Fixed in recent updates.
