### ISSUE TITLE
Dynamic Controller: list, search filter placeholder

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#41]
It would be nice to have the ability to set a text placeholder for search input box alongside with the **"search_fields"**, i.e.
```
"search_fields": "id iname suppliers_iname",
"search_placeholder": "ID, Item, Supplier",
```
or even better, take those text values from **"view_list_map"**

And then display this placeholder in search input list filter

**Comment by osalabs** [comment]
Not sure about autofill placeholder.
For now I've added ability to have `/index/list_filter_search_placeholder.html` where you could put text for placeholder.
