### ISSUE TITLE
Font size looks a bit large on mobile devices

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#5]
#### Propose to decrease in site.css
If the default size is 16px (common setting in modern browsers), then the reduced size will be 14px:

```
@media (max-width: 767px) {
  html {
    font-size: 0.875rem;
  }

  .h1, h1 {
    font-size: 2rem;
  }

  .h2, h2 {
    font-size: 1.75rem;
  }

  .h3, h3 {
    font-size: 1.5rem;
  }

  .h4, h4 {
    font-size: 1.5rem;
  }
}
```

**Comment by osalabs** [comment]
can't agree with that - I prefer to use as pure Bootstrap 4 styles as possible, then particular site can adjust it if necessary
